// <auto-generated />
using AnonymousPhotoBin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AnonymousPhotoBin.Migrations
{
    [DbContext(typeof(PhotoBinDbContext))]
    [Migration("20170919174557_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnonymousPhotoBin.Data.Photo", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<int>("Height");

                    b.Property<string>("Name");

                    b.Property<string>("OriginalFilename");

                    b.Property<int>("PhotoDataId");

                    b.Property<byte[]>("SHA256")
                        .HasColumnType("binary(32)");

                    b.Property<DateTime?>("TakenAt");

                    b.Property<int?>("ThumbnailDataId");

                    b.Property<DateTimeOffset>("UploadedAt");

                    b.Property<int>("Width");

                    b.HasKey("PhotoId");

                    b.HasIndex("PhotoDataId");

                    b.HasIndex("ThumbnailDataId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("AnonymousPhotoBin.Data.PhotoData", b =>
                {
                    b.Property<int>("PhotoDataId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentType");

                    b.Property<byte[]>("Data");

                    b.HasKey("PhotoDataId");

                    b.ToTable("PhotoData");
                });

            modelBuilder.Entity("AnonymousPhotoBin.Data.Photo", b =>
                {
                    b.HasOne("AnonymousPhotoBin.Data.PhotoData", "PhotoData")
                        .WithMany()
                        .HasForeignKey("PhotoDataId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AnonymousPhotoBin.Data.PhotoData", "ThumbnailData")
                        .WithMany()
                        .HasForeignKey("ThumbnailDataId");
                });
#pragma warning restore 612, 618
        }
    }
}
